export const industryData = [
    { id: 1, name: 'Công nghệ thông tin' },
    { id: 2, name: 'Kỹ thuật điện - điện tử' },
    { id: 3, name: 'Xây dựng' },
    { id: 4, name: 'Y tế và chăm sóc sức khỏe' },
    { id: 5, name: 'Giáo dục' },
    { id: 6, name: 'Tài chính - Ngân hàng' },
    { id: 7, name: 'Kế toán - Kiểm toán' },
    { id: 8, name: 'Marketing' },
    { id: 9, name: 'Thương mại điện tử' },
    { id: 10, name: 'Bất động sản' },
    { id: 11, name: 'Luật' },
    { id: 12, name: 'Du lịch và Khách sạn' },
    { id: 13, name: 'Xuất nhập khẩu' },
    { id: 14, name: 'Kỹ thuật cơ khí' },
    { id: 15, name: 'Truyền thông và báo chí' },
    { id: 16, name: 'Nhân sự' },
    { id: 17, name: 'Thiết kế đồ họa' },
    { id: 18, name: 'Nông nghiệp' },
    { id: 19, name: 'Hóa chất và Dược phẩm' },
    { id: 20, name: 'Logistics' },
];
